function [uhel_centrovany] = ZcentrujUhel(uhel_meren, ...
        psi_s1c2, psi_s1c1, psi_s1t1, e_s1t1, e_s1c1, ...
        psi_s2c1, psi_s2c2, psi_s2t2, e_s2t2, e_s2c2, ...
        psi_s1c3, psi_s3c1, psi_s3c3, psi_s3t3, e_s3t3, e_s3c3, ...
        s_t1t2, s_t1t3)

  % 3 pravý, 2 levý, 1 stanovisko

    % Výpočet centrovaného směru na T2
    delta_c2 = CentraciZmena( ...
        psi_s1c2, psi_s1c1, psi_s1t1, e_s1t1, e_s1c1, ...
        psi_s2c2, psi_s2c1, psi_s2t2, e_s2t2, e_s2c2, ...
        s_t1t2);

    % Výpočet centrovaného směru na T3
    delta_c3 = CentraciZmena( ...
        psi_s1c3, psi_s1c1, psi_s1t1, e_s1t1, e_s1c1, ...
        psi_s3c3, psi_s3c1, psi_s3t3, e_s3t3, e_s3c3, ...
        s_t1t3);


   uhel_centrovany = uhel_meren + delta_c3 - delta_c2;

    % Normalizace do intervalu 0–400
    if uhel_centrovany < 0
        uhel_centrovany = uhel_centrovany + 2*pi;
    elseif uhel_centrovany >= 2*pi
        uhel_centrovany = uhel_centrovany - 2*pi;
    end
end
